# Generated by Django 4.1.3 on 2022-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0002_alter_historydataforemailingstat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydataforemailingstat',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
