# Generated by Django 4.1.3 on 2022-12-03 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_ui', '0004_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requests',
        ),
    ]
