# Generated by Django 4.1.3 on 2022-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_dispatch',
            field=models.DateTimeField(verbose_name='Дата отправки'),
        ),
    ]
