# Generated by Django 4.1.3 on 2022-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_mailing_date_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='id_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
